apiVersion: virtex.ai/v1
kind: VoithosAutoscalingGroup
metadata:
  name: "onlineboutique-collision"
spec:
  selector:
    kinds:
    - "Deployment"
    namespaces:
      operator: In
      values:
      - "onlineboutique1"
    workloads:
      operator: In
      values:
      - "frontend"
      - "emailservice"
