apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: emailservice
spec:
  minReplicaCount: 1
  maxReplicaCount: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emailservice
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: paymentservice
spec:
  minReplicaCount: 1
  maxReplicaCount: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: paymentservice
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "70"
  - type: memory
    metricType: Utilization
    metadata:
      containerName: "server"
      value: "70"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: currencyservice
spec:
  minReplicaCount: 1
  maxReplicaCount: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: currencyservice
  triggers:
  - type: memory
    metricType: AverageValue
    metadata:
      containerName: "server"
      value: "200Mi"
  - type: cpu
    metricType: Utilization
    metadata:
      value: "60"
